name: paginate_firestore
description: A flutter package to simplify pagination with firestore data.
version: 1.1.0
homepage: https://github.com/excogitatr/paginate_firestore
issue_tracker: https://github.com/excogitatr/paginate_firestore/issues

environment:
<<<<<<< HEAD
  sdk: ">=3.7.0 <4.0.0"
=======
  sdk: ">=3.5.0 <4.0.0"
>>>>>>> update_versions

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  cloud_firestore: ^5.6.5
  provider: ^6.0.5
=======
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  cloud_firestore: ^5.5.1
  provider: ^6.1.2
>>>>>>> update_versions

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
